#!/bin/sh
# vim:ft=sh

# im going to try weird concurrency stuff right here


listen_for_window_title() {
    # subscribing to regular window events to output title
    # when focus moved to another window or window that is focused changed its title
    jq_filter_window='select(.container.focused and (.change == "focus" or .change == "title")).container.name'
    swaymsg -mt subscribe '["window"]' | jq -r --unbuffered "$jq_filter_window"
}

listen_for_switch_to_empty_workspace() {
    # output empty line when focus is moved to empty workspace

    jq_filter_workspace='select(.change == "focus" and ((.current.floating_nodes | length == 0) and (.current.nodes | length == 0))).current.id'
    swaymsg -mt subscribe '["workspace"]' | jq -r --unbuffered "$jq_filter_workspace" | while read ID; do echo; done
}

# just running this one so i have at least what i had before
listen_for_window_title &
listen_for_switch_to_empty_workspace &
wait
