font=Iosevka:size=12
dpi-aware=no

# initial-window-mode=maximized

[colors-dark]
foreground=dcdcdc
background=000000

regular0=000000

[colors-light]
foreground=000000
background=ffffff

[csd]
preferred=server
hide-when-maximized=yes
