#!/bin/sh
LABEL="${LABEL:-disk}"
MOUNTPOINT="${MOUNTPOINT:-/}"

# Файловая система Размер Использовано  Дост Использовано% Cмонтировано в
# /dev/sda5          167G         141G   18G           90% /
# $1                 $2           $3     $4                $6

usage() {
    df -h $MOUNTPOINT | echo $(awk '{ if (NR == 2) print $6, $3 "/" $2}')
}

echo $LABEL
while read button; do
    if [ -n "$button" ]; then
        echo $LABEL $(usage)
    fi
    read button
    echo $LABEL
done
