#!/bin/sh
LABEL="${LABEL:-disk}"
MOUNTPOINT="${MOUNTPOINT:-/}"

# Файловая система Размер Использовано  Дост Использовано% Cмонтировано в
# /dev/sda5          167G         141G   18G           90% /
#                                        $4                $6

df -h $MOUNTPOINT | awk -v LABEL="$LABEL" '{ if (NR == 2) print LABEL, $6, $4, "free"}'

# resulting line will be 
# disk 18G / free
