#!/bin/sh

if [ -f /sys/class/power_supply/BAT0/charge_now ]; then
    STATUS=$(cat /sys/class/power_supply/BAT0/status)

    # percentage=$(acpi | awk -F ', ' '{print $2}')
    percentage=$(cat /sys/class/power_supply/BAT0/capacity)
    percentage=${percentage%"%"}

    if [ "$STATUS" = Full ]; then
        icon=󱟢
        icon_color='#aaffaa' 
    elif [ "$STATUS" = Charging ]; then
        icon_color='#aaaaff'
        case $((percentage / 10)) in
            0) icon=󰢟 ;;
            1) icon=󰢜 ;;
            2) icon=󰂆 ;;
            3) icon=󰂇 ;;
            4) icon=󰂈 ;;
            5) icon=󰢝 ;;
            6) icon=󰂉 ;;
            7) icon=󰢞 ;;
            8) icon=󰂊 ;;
            9) icon=󰂋 ;;
            10) icon=󰂄
                icon_color='#aaffaa'
                ;;
        esac
    else
        case $((percentage / 10)) in
            0) icon=󰂎
                icon_color='#ffaaaa'
                ;;
            1) icon=󰁺 ;;
            2) icon=󰁻 ;;
            3) icon=󰁼 ;;
            4) icon=󰁽 ;;
            5) icon=󰁾 ;;
            6) icon=󰁿 ;;
            7) icon=󰂀 ;;
            8) icon=󰂁 ;;
            9) icon=󰂂 ;;
            10) icon=󱟢
                icon_color='#aaffaa'
                ;;
        esac
    fi
    if [ -n "$icon_color" ]; then
        icon='<span color="'$icon_color'">'$icon'</span>'
    fi

    if [ "$button" ]; then
        notify-send -h "int:value:$percentage" \
            -a "$icon Battery" \
            -c battery-$STATUS \
            -t 7500 "$(acpi | cut -d ' ' -f 3-)"
    fi

    echo $icon $percentage%
else
    exit 1
fi
