#!/bin/sh

on_update() {
    status="$1"
    if [ "$status" = Playing ]; then
        ICON=
    elif [ "$status" = Paused ]; then
        ICON=
    else
        echo
        return
    fi
    ARTIST="$(playerctl metadata -f '{{artist}}')"
    TITLE="$(playerctl metadata -f '{{title}}')"

    INFO="$TITLE"
    if [ -n "$ARTIST" ]; then
        INFO="$ARTIST - $INFO"
    else
        INFO="$(playerctl metadata -f '{{playerName}}'): $INFO"
    fi

    # PLAYERNAME="$(playerctl metadata -f '{{playerName}}')" 
    # if [ "$PLAYERNAME" = spotify ]; then
    #     ICON="<span color=\"#1ED760\"></span> $ICON"
    # elif [ "$PLAYERNAME" = chromium ]; then
    #     ICON=" $ICON"
    # fi

    # replace & with &amp; (for pango)
    # (discovered with Search & Rescue)
    INFO=$(echo $INFO | sed 's.&.&amp;.')

    echo "$ICON $INFO"
}

playerctl -F status | while read status; do
    on_update "$status"
done &

playerctl -F metadata -f '{{title}}' | while read title; do
    on_update "$(playerctl status)"
done &

while read button; do
    case $button in
        1)
            playerctl play-pause
            ;;
        2)
            echo # hide before status changes
            ;;
        4)
            playerctl position 5-
            ;;
        5)
            playerctl position 5+
            ;;
    esac
done
