#!/bin/sh

LABEL="${LABEL:-ram}"

while IFS=': ' read -r key value _; do
    case $key in
        MemTotal)
            total=$value
            ;;
        MemAvailable)
            avail=$value
            ;;
    esac
done < /proc/meminfo


used=$((total - avail))

printf "$LABEL %d/%d Mi\n" $((used / 1024)) $((total / 1024))
