#!/bin/sh
SEP="${SEP:- | }"
LABEL="${LABEL:-stats}"
MEM_LABEL="${MEM_LABEL:-mem:}"
STORAGE_LABEL="${STORAGE_LABEL:-storage:}"
MOUNTPOINT="${MOUNTPOINT:-/}"

memfree() {
    free -h | awk '/Mem/{print $3 "/" $2 }'
}

storage() {
    df -h $MOUNTPOINT | echo $(awk '{ if (NR == 2) print "\"" $6 "\"", $3 "/" $2}')
}

echo $LABEL
while read button; do
    while echo $MEM_LABEL $(memfree)$SEP$STORAGE_LABEL $(storage); do
        sleep 1
    done &
    read button
    kill $(jobs -p)
    echo $LABEL
done
