#!/bin/sh

# this version works if there is only one adb device connected

# TODO: TO FUCKING DO: CONVERT TO A SCRIPT THAT can handle clicks AND will wait for last serial of matching device and somehow restart itself or something

LABEL="${LABEL:-$DEVICE_PATTERN}"

if [ -n $DEVICE_PATTERN ]; then
    # i like shell scripting here because i don't need to do shit for this to work
    # adb itself uses this environment variable
    export ANDROID_SERIAL=$(adb devices -l | awk '/'"$DEVICE_PATTERN"'/ {print $1; exit}')
    # adb uses this variable even if it is empty
    if [ -z $ANDROID_SERIAL ]; then
        echo
        exit
    fi
fi

if adb shell exit 0; then
    LEVEL=$(adb shell 'dumpsys battery | awk "/level/{print \$NF}"')
    CHARGING=$(adb shell dumpsys battery | awk '/status/ {if ($NF == 2) print "charging"}')
else
    echo
    exit
fi

BATTERY=
COLOR=

if [ $LEVEL -lt 50 ]; then
    COLOR='#aaaa50'
elif [ $LEVEL -ge 85 ]; then
    COLOR='#50aa50'
else
    COLOR='#ffffff'
fi

if [ -n "$CHARGING" ]; then
    # BATTERY=󰂄
    BATTERY=󰂅
    BATTERY='<span fgcolor="'$COLOR'">'$BATTERY'</span>'
else
    BATTERY=󰁹
fi

echo $LABEL $LEVEL% $BATTERY # full_text
# echo $LEVEL% # short_text
echo # short_text

echo # color
echo # bg color
